### ISSUE TITLE
Need further help to build hs-ogdf

### ISSUE THREAD

**Issue by WolfgangSpahn** [wavewave/fficxx-projects#2]
Your project looks very promising for my need to use ogdf from Haskell. I can build nix packages via `nix-build release.nix`, after having done `git clone https://github.com/wavewave/fficxx.git`, which gives me
```
- /nix/store/g8r5lm1k13dh5dpimq1wnd9ydvks8r02-fficxx-0.6
- /nix/store/47x9acc8aps5qxwl3wk0445qgz79md3y-fficxx-multipkg-test-0.6
- /nix/store/lpiy8p5ha6lmqanpfbbnm98l2b33lyp9-fficxx-runtime-0.6
- /nix/store/1g0dxrbcd9alz92lamkhv1c8v4m7w752-fficxx-test-0.6
- /nix/store/r6glb46f1dgwclb9mpxc9mp8r4a4cnsi-stdcxx-0.6
- /nix/store/dqcz5w2f59avmzd5n6rr44giyal5lc75-tmpl-dup-inst-0.0
```

But after cloning the project repo: `clone https://github.com/wavewave/fficxx-projects.git`
hs-ogdf is empty, trying `git clone --recurse-submodules https://github.com/wavewave/fficxx-projects.git` failed. It seams I would need a key. And populating it via getting the content via `unzip ~/Downloads/hs-ogdf-2e385e12d59b2d432b54f6ff607e7b3b5f6d4366.zip` does not succeed either:

```
nix-build release.nix 
error: getting attributes of path '/home/wolf/Projects/Haskell/MyPackages/fficxx-projects/fficxx': No such file or directory
```
What do I have to do to build hs-odgf? I am new to use nix, building Haskell. So mistake is probably with me.

Thanks in advance for looking into it.

**Comment by wavewave** [comment]
Hi,
Thanks for trying. Interesting. It should not be a key problem.
I just use the same command `git clone --recurse-submodules https://github.com/wavewave/fficxx-projects.git` on "empty" directory and `nix-build release.nix -A OGDF` worked well (with correct submodule populated)

If submodule does not work for some reason, `git clone` per each subdirectory of `fficxx-projects`.  From this repo's root in github webpage, you see what the git commit SHA of each submodule is. You will need the directories `fficxx` and `hs-ogdf` to be filled with the contents in order to proceed.
Hope that the process will be smooth afterwards.

**Comment by wavewave** [comment]
now with nix >= 2.4, `nix build .#OGDF` will build it. no more submodule.
